<a href="https://colab.research.google.com/github/prachimethi/assignment/blob/main/Numpy_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Therotical** **Questions**:-

Ques-1 Explain the purpose and advantage of numpy in scientific computing and data analysis. how does it enhance python's capabilities for numerical operations?

ans- Purpose of NumPy
Efficient Storage and Manipulation of Arrays: NumPy provides a powerful N-dimensional array object, ndarray, which allows for efficient storage and manipulation of large datasets.

Mathematical Functions: It offers a wide array of mathematical functions to perform operations on arrays, making it easier to conduct complex numerical analyses.

Integration with Other Libraries: NumPy serves as the foundational library for many other scientific libraries, such as SciPy, Pandas, and Matplotlib, creating a robust ecosystem for scientific computing.

Advantages of NumPy
Performance: NumPy is implemented in C, making its operations significantly faster than pure Python, especially for large datasets. Its operations are optimized for performance.

Convenience: The ndarray structure supports a variety of operations (e.g., element-wise operations, broadcasting, etc.) that simplify coding and make it more intuitive for users familiar with mathematical notation.

Memory Efficiency: NumPy arrays consume less memory compared to Python lists. The homogeneous nature of arrays allows for better memory allocation and performance.

Rich Functionality: NumPy provides extensive functionality, including linear algebra operations, Fourier transforms, random number generation, and more, allowing for comprehensive data analysis.

Support for Multi-dimensional Data: It easily handles multi-dimensional arrays, enabling complex data structures that are essential for many scientific applications.

Broadcasting: This feature allows operations between arrays of different shapes, facilitating more intuitive mathematical operations without the need for explicit loops.

Enhancement of Python’s Numerical Capabilities
Array Operations: NumPy allows for concise array operations without the need for explicit loops, which not only simplifies the code but also enhances performance.

Vectorization: Many operations can be performed on entire arrays rather than individual elements, which reduces execution time and improves readability.

Integration with C/C++ and Fortran: NumPy can interface with code written in C, C++, or Fortran, enabling users to optimize performance-critical sections of their applications.

Interoperability: NumPy arrays can be easily used with other libraries, enhancing Python's overall numerical capabilities. For instance, arrays can be directly utilized in libraries like SciPy for advanced mathematical computations or Matplotlib for plotting.

Ques-2 compare and contrast np.mean() and np.average() functions in numpy. when would you use one over the other.

Both np.mean() and np.average() are functions in NumPy used to compute the average of array elements, but they have some key differences in functionality and usage. Here’s a comparison:

np.mean()

Purpose: Computes the arithmetic mean (average) of the array elements along the specified axis.
Syntax: np.mean(a, axis=None, dtype=None, keepdims=False, ...)

np.average()

Purpose: Computes the weighted average of the array elements. It can also compute the arithmetic mean if no weights are provided.
Syntax: np.average(a, axis=None, weights=None, returned=False)

ques-3 Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
arrays.

In [ ]:
import numpy as np

In [ ]:
#reversing a numpy array
a= np.array([1, 2, 3, 4, 5])

In [ ]:
np.flip(a)

array([5, 4, 3, 2, 1])

In [ ]:
#example of 1 d array
ab = np.array((1, 2, 4, 5, 7, 8))
ab

array([1, 2, 4, 5, 7, 8])

In [ ]:
#example of 2d array
b = np.array(([1, 2, 3],[4, 5, 7]))
b

array([[1, 2, 3],
       [4, 5, 7]])

Ques-4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types
in memory management and performance.

In [ ]:
b

array([[1, 2, 3],
       [4, 5, 7]])

In [ ]:
b.dtype

dtype('int64')

Importance of Data Types in Memory Management and Performance
Memory Management:

Size: Different data types consume different amounts of memory. For instance, int8 uses 1 byte, int16 uses 2 bytes, and so on. Choosing an appropriate data type can save memory, especially when dealing with large datasets.
Type Consistency: Using consistent data types helps avoid errors in computations and improves memory efficiency. For instance, using a float type when you expect decimal values prevents unnecessary type conversion during calculations.

Performance:

Speed: Operations on smaller data types (e.g., int8 vs. int64) can be faster because they require less memory bandwidth and can take advantage of CPU registers more efficiently.
Vectorization: NumPy is optimized for operations on arrays of uniform data types, allowing for efficient use of vectorized operations. Mixed data types can lead to slower performance due to the overhead of type conversion during calculations.


Ques-5 Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

ndarrays (N-dimensional arrays) are the central data structure used for storing and manipulating large datasets. They are more efficient and versatile than standard Python lists, making them a cornerstone of numerical computing in Python. Here’s an overview of their key features and how they differ from Python lists:

Key Features of ndarrays



1. Homogenous data type
2. multidimensional
3. efficient memory location
4. element wise operations
5. broadcasting
. rich functionality
7. shape and size information
8. advanced indexing and slicing



Ques-6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

NumPy arrays provide several performance benefits over Python lists, especially for large-scale numerical operations:

1. Memory Efficiency
2. speed
3. vectorization
4. broadcasting
5. built in functions
 . parrellization
7. interoperability


ques-7 Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
output.

In NumPy, vstack() and hstack() are functions used to stack arrays vertically and horizontally, respectively. Here's a detailed comparison along with examples for each.

In [ ]:
#vstack example
import numpy as np
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

result_vstack = np.vstack((array1, array2))
print(result_vstack)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
#hstack example
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8],
                   [9, 10]])

# Use hstack to stack them horizontally
result_hstack = np.hstack((array1, array2))
print(result_hstack)



[[ 1  2  3  7  8]
 [ 4  5  6  9 10]]


Ques-8  Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
array dimensions.




In NumPy, the fliplr() and flipud() functions are used to flip arrays along different axes. Here's a breakdown of their differences and effects on various array dimensions:

fliplr()
Functionality: This function flips an array left to right (along the horizontal axis).

Applicable Dimension: Primarily operates on 2D arrays (matrices). When applied to higher-dimensional arrays, it flips the last axis by default.

In [ ]:
#example
import numpy as np
arr = np.array([[1, 2, 3],
                [4,5,7]])
np.fliplr(arr)

array([[3, 2, 1],
       [7, 5, 4]])

Flipud()
Functionality: This function flips an array up to down (along the vertical axis).

Applicable Dimension: Similar to fliplr(), it mainly works on 2D arrays. For higher-dimensional arrays, it flips along the first axis by default.

In [ ]:
#example
np.flipud(arr)

array([[4, 5, 7],
       [1, 2, 3]])

Ques-9  Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

In [ ]:
#The array_split() method in NumPy is used to divide an array into multiple sub-arrays along a specified axis. Here's a detailed look at its functionality,
# including how it handles uneven splits.
#example
arr

array([[1, 2, 3],
       [4, 5, 7]])

In [ ]:
np.array_split(arr, 2, axis =0)

[array([[1, 2, 3]]), array([[4, 5, 7]])]

Ques-10 Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array
operations?

Vectorization optimizes computations by avoiding explicit loops, leveraging efficient array operations.

Broadcasting enables flexible array interactions by automatically aligning shapes, making it easier to perform calculations without extra memory overhead.

**PRACTICAL** **QUESTIONS**

Ques-1  Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [17]:
import random
A = np.random.randint(1,100,(3,3))
A

array([[40, 43, 66],
       [ 8, 90, 49],
       [95, 80, 99]])

In [27]:
A.T

array([[40,  8, 95],
       [43, 90, 80],
       [66, 49, 99]])

Ques-2  Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [36]:
  B = np.array([[1,2,3,4,5],[4,5,7,8,9]])
  B

array([[1, 2, 3, 4, 5],
       [4, 5, 7, 8, 9]])

In [39]:
np.random.randint(1,10,(5,2))


array([[1, 5],
       [7, 6],
       [5, 3],
       [5, 7],
       [9, 6]])

In [40]:
B.reshape(2,5)

array([[1, 2, 3, 4, 5],
       [4, 5, 7, 8, 9]])

Ques-3 . Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array

In [49]:
arrr = np.random.randint(1,10,(4,4))
arrr

array([[2, 2, 6, 4],
       [5, 1, 1, 4],
       [9, 5, 9, 4],
       [2, 3, 8, 4]])

In [50]:
bordered_array = np.pad(arrr, pad_width=1, mode='constant', constant_values=0)

print("\nArray with a Border of Zeros:")
print(bordered_array)


Array with a Border of Zeros:
[[0 0 0 0 0 0]
 [0 2 2 6 4 0]
 [0 5 1 1 4 0]
 [0 9 5 9 4 0]
 [0 2 3 8 4 0]
 [0 0 0 0 0 0]]


Ques-4  Using NumPy, create an array of integers from 10 to 60 with a step of 5

In [51]:
np.arange(10,60,5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

Ques-5  Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
(uppercase, lowercase, title case, etc.) to each element.

In [53]:
string = np.array(['python', 'numpy','pandas'])
string

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [54]:
np.char.upper(string)

array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6')

In [55]:
np.char.capitalize(string)

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

In [56]:
np.char.lower(string)

array(['python', 'numpy', 'pandas'], dtype='<U6')

Ques-6. Generate a NumPy array of words. Insert a space between each character of every word in the array

In [59]:
words= np.array(['hello','mine','teddy'])
space = np.array([' '.join(word)for word in words])
space

array(['h e l l o', 'm i n e', 't e d d y'], dtype='<U9')

Ques-7  Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division

In [64]:
a = np.array(([1, 2, 3, 4, 5]))
b = np.array(([7 ,8 , 9, 5 ,4]))

In [65]:
a + b

array([ 8, 10, 12,  9,  9])

In [66]:
a - b

array([-6, -6, -6, -1,  1])

In [67]:
a*b

array([ 7, 16, 27, 20, 20])

In [68]:
a / b

array([0.14285714, 0.25      , 0.33333333, 0.8       , 1.25      ])

Ques-8 Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [71]:
ab = np.eye(5)
ab

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [72]:
np.diagonal(ab)

array([1., 1., 1., 1., 1.])

Ques-9  Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
this array.

In [91]:
import numpy as np

# Generate a NumPy array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1000, size=100)

# Function to check if a number is prime
def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True

# Find all prime numbers in the array
prime_numbers = np.array([num for num in random_integers if is_prime(num)])

# Print the results
print("Random Integers:")
print(random_integers)

print("\nPrime Numbers:")
print(prime_numbers)


Random Integers:
[958 541 101 688 270 687 715 621 740 607 559  34 672 935 450 503 860 999
 675 944 470 584 561 258 673 884 757 174 428 830 797 917 813 921 159 321
 314 118  39  15 866 328 369 867 902 694 693 646 891 923 244 522 263 628
 455 545 547 627 108 968 887 924 978 126 994 816 474 576  57 700 701 697
 522 962 253 452 912 740 194  99 151  96 427 614 360 114 590 492 968 868
 664 634 272 400   8  64 563 581 954 225]

Prime Numbers:
[541 101 607 503 673 757 797 263 547 887 701 151 563]


Ques-10  Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
averages.

In [96]:
monthly = np.random.uniform(low=15, high=30,size=30)
weekly_temperatures = np.reshape(monthly,(5,6))
np.mean(weekly_temperatures,axis=1)

array([22.37020532, 23.02477391, 20.64999959, 26.12388667, 22.93042873])